WITH CTE AS(
SELECT M.CUSTOMER_ID, S.ORDER_DATE, S.PRODUCT_ID FROM MEMBERS AS M
INNER JOIN SALES AS S
ON S.CUSTOMER_ID=M.CUSTOMER_ID
WHERE EXTRACT(DAY FROM S.ORDER_DATE) BETWEEN EXTRACT(DAY FROM M.JOIN_DATE) AND 7+EXTRACT(DAY FROM M.JOIN_DATE)
),
CTE2 AS(
SELECT M.CUSTOMER_ID, S.ORDER_DATE, S.PRODUCT_ID FROM MEMBERS AS M
INNER JOIN SALES AS S
ON S.CUSTOMER_ID=M.CUSTOMER_ID
WHERE ORDER_DATE NOT IN (SELECT ORDER_DATE FROM CTE)
),
CTE3 AS(
SELECT C1.CUSTOMER_ID,MN.PRICE,C1.ORDER_DATE
FROM MENU AS MN
INNER JOIN CTE AS C1
ON MN.PRODUCT_ID = C1.PRODUCT_ID
),
CTE4 AS(
SELECT C2.CUSTOMER_ID,MN.PRICE,C2.ORDER_DATE
FROM MENU AS MN
INNER JOIN CTE2 AS C2
ON MN.PRODUCT_ID = C2.PRODUCT_ID),
CTE5 AS(
SELECT CUSTOMER_ID,PRICE*20 AS POINTS FROM CTE3
UNION
SELECT CUSTOMER_ID, PRICE*10 AS POINTS FROM CTE4),
CTE6 AS(
SELECT CUSTOMER_ID,
SUM(POINTS) OVER(PARTITION BY CUSTOMER_ID ORDER BY CUSTOMER_ID) AS TOTAL_REWARD
FROM CTE5)

SELECT * FROM CTE6
GROUP BY CUSTOMER_ID, TOTAL_REWARD