WITH RANK AS(SELECT CUSTOMER_ID,PRODUCT_ID,COUNT(*),
RANK() OVER(PARTITION BY CUSTOMER_ID ORDER BY COUNT(*) DESC)
FROM SALES
GROUP BY CUSTOMER_ID,PRODUCT_ID)

SELECT CUSTOMER_ID, PRODUCT_NAME FROM MENU AS M
INNER JOIN RANK AS R
ON R.PRODUCT_ID=M.PRODUCT_ID
WHERE RANK =1


