WITH CTE AS(SELECT M.CUSTOMER_ID,S.PRODUCT_ID FROM MEMBERS AS M
INNER JOIN SALES AS S
ON M.CUsTOMER_ID = S.CUSTOMER_ID
WHERE M.JOIN_DATE > S.ORDER_DATE)

SELECT C.CUSTOMER_ID,SUM(PRICE) FROM CTE AS C
INNER JOIN MENU AS MN
ON MN.PRODUCT_ID= C.PRODUCT_ID
GROUP BY CUSTOMER_ID